### ISSUE TITLE
Remove old dumps

### ISSUE THREAD

**Issue by MCOfficer** [MCOfficer/odcrawler-discovery#49]

**Comment by Chaphasilor** [comment]
How old are we talking? xD

**Comment by MCOfficer** [comment]
I've been cleaning manually, but basically *anything that isn't the current dump*.

**Comment by Chaphasilor** [comment]
Yeah I guess there's no reason to keep older dumps...

**Comment by MCOfficer** [comment]
the only reason to keep them is in case people were still downloading - but linux does that for us, it will only be deleted as soon as nobody is reading from/writing to the file.
